# Browser Configuration
url=https://admin-demo.nopcommerce.com/login?returnUrl=%2Fadmin%2F
browser=chrome
# Credentials
admin_email=admin@yourstore.com
admin_password=admin
# Timeouts
implicit_wait=10
page_load_timeout=30